# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with H2
      run: mvn -B clean test
    - name: Test with PostgreSQL
      run: mvn -B clean test -Ppostgresql
    - name: Test with Oracle
      run: mvn -B clean test -Poracle
    - name: Test with MySQL
      run: mvn -B clean test -Pmysql
    - name: Test with SQLServer
      run: mvn -B clean test -Psqlserver
    - name: Test with IBM DB2
      run: mvn -B clean test -Pdb2
